### ISSUE TITLE
Cannot create vertically-oriented legend at bottom of chart

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#103]
I have a need to create a vertically oriented legend underneath a pie chart, but the code in `Chart.LoadLegend()` automatically resets the orientation to horizontal based on the `LegendLocation` property.

**Comment by beto-rodriguez** [comment]
Sadly you need to create your own legend for this:

http://lvcharts.net/#/examples/v1/legend-wpf?path=WPF-Components-Legend

Because in previous versions you could configure the orientation this might work:

```c#
myChart.Legend = new ChartLegend {Orientation = Orientation.Vertical};
```

The orientation property was used in previous versions, and this will work for now but it is not guaranteed to be supported in future versions, you might normally need to create your own control.

There is no a good tutorial about it, but it is the same as creating your own tooltip and I built a nice example for that, let me know if this helps you.

http://lvcharts.net/#/examples/v1/tooltips-wpf?path=WPF-Components-Tooltip

**Comment by beto-rodriguez** [comment]
When you need a special tooltip or legend you can easily create your own.

Sadly I haven't built a nice example for this but I explain here what you need to do:

http://lvcharts.net/#/examples/v1/legend-wpf?path=WPF-Components-Legend

And here is a good example of how to build your own tooltip, it is the same logic with legends, I think you will get it if you read both articles.

http://lvcharts.net/#/examples/v1/tooltips-wpf?path=WPF-Components-Tooltip

The idea is simple you will provide your own user control with your requirements, and LiveCharts will inject the DataContext with the series information, the chart should respect the size of your control and plot correctly (I have not tested this) please let me know the results.

**Comment by beto-rodriguez** [comment]
I am closing this issue if you need more help please let me know
