### ISSUE TITLE
Chart not drawing when I do constant changes in a short period or time (less than 100ms).

### ISSUE THREAD

**Issue by GregRos** [beto-rodriguez/Live-Charts#105]
Adding points to a line chart with frequency higher than around 10 Hz causes it to freeze. Calling `Update` does nothing. Calling `UpdateUnsafe` does unfreeze the chart, but it quickly goes crazy.

If you have several chart controls on a single page, they behave erratically even at 2 Hz (I had 4 of them). They can freeze randomly, the line gets distorted, etc.

I understand that the library has performance limitations, but it would be great if they were handled correctly. I spent a few hours trying to figure out what was wrong.

**Comment by beto-rodriguez** [comment]
This is a new library and it is in a beta version, this library has changed a lot since first version and that is the only reason why high performance charts are not ready yet. 

Charts are not freezed, they just don't have enough time to update. http://lvcharts.net/#/examples/v1/howitworks?path=howitworks currently 0.6.5 needs 100ms without changes to update the chart, I will fix this when I release high performance charts, I have been working in some algorithms that makes this library able to plot 3 millions points in 1 second, but because of the constan evolution of this library it is hard to keep them updated, I think this library is mature enough now to update the high performance algorithms.

please be patient and feel free to contribute, high performance charts are not ready yet but trust me, I have been working on it and this library will be able really fast compared to any other libraries, we just need some time and fix the reported issues before I can release 1.0 a really solid product.

**Comment by GregRos** [comment]
I understand the performance limitations, that's understandable. My real problem is that, as a user, I had no idea why the chart wasn't updating. It decided to update when I resized it, so I thought it was some kind of issue involving invalidation/redrawing.

Isn't it possible to give some indication about what's going on? E.g. if it misses too many updates, it throws an exception or gets a red background and outputs something to the debug log, and there could be a property like `DebugMode` to control the functionality, and it would be on by default. I think that if you're using these kinds of algorithms, it's best to have this functionality even if you do improve performance.

**Comment by beto-rodriguez** [comment]
@GregRos I am sorry for the inconvenience I have not documented this behavior because I need to change that, this wont happen in future versions.

This concept is necessary to keep charts running smoothly, other wise the chart would redraw every time you change any point and will result in a horrible performance.

Now there is a timer with a tick of 100ms, every tick the chart updates, the timer restarts every time you change your data, since you change your data in a lower frequency than this timer interval, then the timer never ticks and is not able to redraw.

I will rename and keep your issue open so others know about this, for now you need at least 100 ms without data changes so the chart can be redrawn.

**Comment by GregRos** [comment]
That's not the only issue though. As I've said, with 4 charts, some will freeze even at 2 Hz (500 ms) and there are all kinds of visual artifacts.

It's really unfortunate. I guess I'll have to use OxyPlot after all. Yours is much cooler, though.

**Comment by beto-rodriguez** [comment]
Oxyplot is really good, but I started this library because Oxyplot was not enough for me.

it is just matter of time and work to fix that issue you are facing, sadly I am not able to force it, can I please see your code? 

this library (and every other open source projects) gets stronger with each new issue, it would be awesome if you share your code with me so I can work on it, sooner or latter it will work as you need, oxyplot was released years ago, this library has only a few months and we are really close to any other chart library now, as I said is just a matter of time and work.

The more you share and help the faster we can release a 1.0 version.

**Comment by GregRos** [comment]
Yeah, that's why I didn't like Oxyplot. It's kind of ugly and requires some setup to look better. In addition, it's rather slow for my purposes as well.

I'll happily share my code with you, but I'm not at work anymore. I'll send it next week. It's just some observables generating random output.

**Comment by GregRos** [comment]
By the way, what tool did you use to generate the documentation in the documentation site?

**Comment by beto-rodriguez** [comment]
Javascript, Html and css, I built it

**Comment by GregRos** [comment]
Ow. I thought you had some kind of cool generator.

I have an almost fully documented library (in XML doc) ([Imms](https://github.com/Imms/Imms)) and I wanted to generate documentation for it. I use Sandcastle for generating the API documentation, but I want to add some conceptual documentation, and in Sandcastle you can only do that with a *horrible, horrible* XML-type syntax (it manages to be even worse than XmlDoc). I tried to use it, but I have a rather fragile psyche. So I want to find something that parses .NET and Markdown. It looks like I'm going to have to use Doxygen, and somehow style it better (I don't like how it tends to generate documentation).

I was planning to write the landing page in JS, but writing the whole thing like that seems like too much work.

**Comment by beto-rodriguez** [comment]
my cool generator is Angular js, I have only 4 views and angular does it all.

**Comment by laoyur** [comment]
Hi, is there any update to this issue ?

**Comment by beto-rodriguez** [comment]
working on it on another branch https://github.com/beto-rodriguez/Live-Charts/tree/Portable
