### ISSUE TITLE
Bar Chart - X-Axis creates unreadable labels

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#12]
The line chart seems to handle labels for a lot of data better than the bar chart does. I would like if they were setup similar. I attached screenshots showing what I am talking about. These are using the same exact data.

![image](https://cloud.githubusercontent.com/assets/14826876/10120083/3365ec74-6479-11e5-8acf-9ceecb2e13f9.png)

![image](https://cloud.githubusercontent.com/assets/14826876/10120087/3f4a0016-6479-11e5-8fa7-cb3bed12ab58.png)

**Comment by beto-rodriguez** [comment]
Default Barchart separator was 1, because normally bar charts don't have many points, in your case if you have many points, I added a new property to `Separator` of type `double?`, by defualt it is 1, if you want to get the behavior a line chart has you need to set it to null. I added an example in test project because maybe this will be a common issue. Thank again!

**Comment by beto-rodriguez** [comment]
this is now totally automatic
