### ISSUE TITLE
When adding multiple BarSeries to a BarChart getting error if one value is 0

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#13]
The error thrown is

Exception thrown: 'System.ArgumentException' in WindowsBase.dll

Additional information: '-0.62894699242749' is not a valid value for property 'Width'.

**Comment by beto-rodriguez** [comment]
I already fixed some bugs you posted, thank you very much I am posting a commit as soon as possible because I added 2 new charts, StackedBar and Radar, Ill try to reproduce this bug with the info you gave, but it would be better if you show me an example. thank you very much for your help!

![image](https://cloud.githubusercontent.com/assets/10853349/10128109/4837eada-6573-11e5-8d87-f5897b4b8ad7.png)

**Comment by beto-rodriguez** [comment]
I tried with this series and everything is running ok.

```

**Comment by lrmills85** [comment]
I am not able to duplicate this now. Thanks!

**Comment by harshasudhakar** [comment]
I have problem with 'NaN' is not a valid value for property 'To'. in pie charts wpf. so please help me out.
 PointLabel = chartPoint => string.Format("{0}", chartPoint.Y, chartPoint.Participation); when the 0/0 value is undefined.
