### ISSUE TITLE
How to realize the rolling effect in a linechart?

### ISSUE THREAD

**Issue by adwardy** [beto-rodriguez/Live-Charts#134]
Hi. I am trying to realize a rolling effect in a linechart. When a new point is come, I push the point to the back of the Series and remove the first point in the Series:
` if (AttChartSeries[0].Values.Count >= 300)
  {
        AttChartSeries[0].Values.RemoveAt(0);                               
  }
  AttChartSeries[0].Values.Add(new Point(deltaTime.TotalSeconds, dataParser.Roll));`
But, the starting point of the Axis X is always 0, not the x component of the current first point in the Series. As a result, the left part of the plotted line appears as empty as time going.
I don't know how to fix this problem. 
Looking forward to your answer. Thanks!

**Comment by beto-rodriguez** [comment]
Hello are you plotting double values? or a class?

I tried to explain how live charts works here, http://lvcharts.net/#/examples/v1/howitworks?path=howitworks I think this might help

the animations can behave different when you use a class instead of primitive types, primitive types are harder to track, using a class will always improve animations.

I hope it helps but I think I need more info to help you better.

**Comment by beto-rodriguez** [comment]
I am afraid I don't fully understand you, What do you mean with roll effect? 

tracking changes is tricky, using primitives and maybe structs as Point could not display the correct animation (I am not sure about structs have not tested it) as I try to explain here http://lvcharts.net/#/examples/v1/howitworks?path=howitworks

please let me know more about this, also instead of using the struct Point try a user define class, this will improve animations tracking.

```
public class MyPoint
{
  public double X {get;set;}
  public double Y {get;set;}
}

```

**Comment by adwardy** [comment]
I do use a class named Point defined by myself, just the same as your MyPoint class above.
Roll effect means the the line move from right to left when a new point arrives. The capacity of the Series is fixed. When a new point comes, the oldest point is remove from the line.  
Actually, I do this in order to avoid the accumulation of the data in the chart to fix the plotting time and improve the fluency of the program.

**Comment by adwardy** [comment]
The problem is solved. There are three line series in my chart. Only one line is set as dynamic, and the other two line stay static when debugging. As a result, the problem appears.

Thanks!
