### ISSUE TITLE
LineSeries Performance for 10,000 points

### ISSUE THREAD

**Issue by cschiano** [beto-rodriguez/Live-Charts#139]
Hello Alberto,

First, I'd like to thank you for your impressive library. I use Oxyplot but LiveCharts seems really interesting. However I have a performance issue with the code below (10,000 random points). I tried to disable animations, to set line smoothness to 1 but no matter what I do, the rendering time is more than 3 seconds. I looked at the performance section in the source code but it seems outdated. Could you please help me?

Thank you,
Clément

ViewModel:
```
public SeriesCollection Series { get; set; } = new SeriesCollection();

public void Draw()
{
    var chartValues = new ChartValues<double> { };
    var random = new Random();
    for (var i = 0; i < 10000; i++)
    {
        chartValues.Add(random.NextDouble() * i);
    }

    var lineSeries = new LineSeries { Values = chartValues };
    Series.Add(lineSeries);
}
```
View:
```
<liveCharts:LineChart LegendLocation="Right" Series="{Binding Series}"/>
```

**Comment by beto-rodriguez** [comment]
Hello, and thanks, 10,000 random points could be plotted in 70ms according to the tests I did, 
but it is another package:

https://www.nuget.org/packages/LiveCharts.Optimizations/0.1.2.1

This package is a virtualizer, it uses some algorithms I am working with to improve drastically the performance, as you noticed from 3,000 ms to 70 ms

but because of the changes in this library they are not ready yet, actually the new version (0.7.0) should be much more fast than those 3,000 ms 

0.7.0 will be the last big design change in LiveCharts, this version will extend the library to UWP and Xamarin.

When Optimizations are ready I will let you know, but they are in another package and depending on the evolution of the library maybe it will have a small price, not sure yet

Thanks

**Comment by cschiano** [comment]
Thank you for your answer,
I'll use the LiveCharts.Optimizations library but I can't wait to see the new version in action!
