### ISSUE TITLE
ToolTip is not visible when the series data is set via code MMVM

### ISSUE THREAD

**Issue by amoudanjames1** [beto-rodriguez/Live-Charts#140]
Hi,
I am working on a wpf charting application and I want to use the live chart library version  0.5.8.0.
Development environment is VS 2013 (framework 4.0).

Its a simple line chart with multiple series. If the series data is hardcoded in xaml, the graph does shows the tooltip. However if the data is binded via MVVM, the graph does not show the tooltip. 
I even tried Hoverable property, but I do not get the desired result.

The WPFExample found along with your code does exhibit the same behaviour. (MvvmLine example).

Is it a bug or a default behaviour? Can you please help me.

Thanks
Alex

**Comment by beto-rodriguez** [comment]
Many things have happened since 0.5.8, you need to use a newer version, this project is in a beta state so we don't have yet a really solid and stable version, but the closest to it would be 0.6.4, the most animated (but with some issues reported) is 0.6.7, 0.6.6 is also a good version but you will face performance issues in line charts.

please use any of those versions and let me know if this issue continues.

those 3 versions contains practically the current code of the library.

Thanks!

**Comment by amoudanjames1** [comment]
Thanks for your reply. Let me try and get back to you.
Thanks

**Comment by beto-rodriguez** [comment]
Closing this issue, because 0.5 version is much different, I am just about to publish 0.7.0 let me know if you still having any troubles in the future!

**Comment by amoudanjames1** [comment]
Thanks. Indeed the newer version did solved the issue. 

Best regards,

Alex

 

De : Alberto Rodríguez [mailto:notifications@github.com] 
Envoyé : lundi 16 mai 2016 05:35
À : beto-rodriguez/Live-Charts
Cc : Amoudan Alex; Author
Objet : Re: [beto-rodriguez/Live-Charts] ToolTip is not visible when the series data is set via code MMVM (#140)

 

Closing this issue, because 0.5 version is much different, I am just about to publish 0.7.0 let me know if you still having any troubles in the future!

**Comment by stefanofalasca** [comment]
Hi I don't know if this problem, but I dont' use MVM to set data series, and tooltip is not showed. I set follow mode:

var tooltip = new DefaultTooltip { SelectionMode = TooltipSelectionMode.SharedYValues };
chart.DataTooltip = tooltip;
