### ISSUE TITLE
Assigning set of colors to a chart using MVVM or code behind

### ISSUE THREAD

**Issue by rohit3d2003** [beto-rodriguez/Live-Charts#158]
How do we specify set of colors for a particular chart? It seems we cannot bind the Colors property to a List defined in ViewModel. I looked at other examples and it uses a single stroke with different color options for fill. I am trying to specify a collection of color with a given stroke and fill

**Comment by beto-rodriguez** [comment]
The Chart.Colors property is static, so it is shared for all the charts in your application, this is intentional of course to have a base default color set for the application.

you can customize this property and change the colors set as explained here http://lvcharts.net/#/examples/v1/series-colors-wpf?path=WPF-Components-Series

This property can not be specified only for an instance, and I really do not see why it should, in that case you must set the Fill and color for each series:

```c#
var mySeries = new LineSeries { Stroke = Brushes.Red, Fill =  Brushes.Blue };
```

```xml
<lvc:LineSeries Stroke="Red" Fill="Blue" />
```

if you disagree with me please let me know why

Note: Please use stack overflow for questions, add the tag LiveCharts I will answer as soon as possible.

**Comment by rohit3d2003** [comment]
Sorry for putting it here, I will post all further questions on stack overflow. It is just a cosmetic thing where you may want to cycle through a set of base colors for your chart. I have a User Control where I am displaying 5 charts and want them to cycle through different set of colors.

**Comment by beto-rodriguez** [comment]
then you have 2 options:

1) set those default colors in all your application:

```c#
Chart.Colors = new List<Color>
{
  Colors.Red,
  Colors.Green,
  Colors.Blue
};
```

2) if you only need it for those 5 specific charts, then pull it automatically from your list, for example:

```c#

var myColors = new List<Color>
{
  Colors.Red,
  Colors.Green,
  Colors.Blue
};

var index = 1 ; //get color at 1, or 2, what ever the next formula will pull the next color.

//this is actually what I do to get the colors:
var colorByIndex = myColors[(int)(index - myColors.Count * Math.Truncate(index / (decimal) myColors.Count))]

```

**Comment by rohit3d2003** [comment]
Worked for me! thank you
