### ISSUE TITLE
Only Piechart and CartesianChart in WPF

### ISSUE THREAD

**Issue by panhans** [beto-rodriguez/Live-Charts#174]
I'm not able to use LineChart, BarChart ect. anymore. Only Piechart and CartesianChart exist.

**Comment by beto-rodriguez** [comment]
Yeah, that is totally intentional, you actually have 3 charts, PieChart, CartesianChart and Gauge.

The cartesian charts supports many new series, and you can also mix them all, Lines, Bars, StackedAreas, StackedBars, Bubbles, Ohcl (Financial).

The cartesian chart is much more smarter than old dedicated charts (linechart, barcharts, stackedbarchart)

you can pull any series in a cartesian chart and it will work

I am updating the website with the new docs...

I recommend you to read https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.7.0
you can also find examples at https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart

0.7.0 should be much easier there are a lot of automated stuff now

Sorry about changing the library but it is a small change and will allow you to do much more stuff.

Hope this guide you!

**Comment by beto-rodriguez** [comment]
new documentation already includes and explain this, please let me know if you have any other issue

http://lvcharts.net/App/examples/wpf/start

Thanks!
