### ISSUE TITLE
StackedCollumnSeries Inverted Labels

### ISSUE THREAD

**Issue by camou23** [beto-rodriguez/Live-Charts#209]
I dont know if its really a Bug or i'm doing something wrong.
The Labels from the Mouseoverlay are Inverted with the Values from the Chart.

![image](https://cloud.githubusercontent.com/assets/4669637/16079533/451a5bee-3304-11e6-8380-2b1d2b49b050.png)

**Comment by beto-rodriguez** [comment]
I am not sure about this anymore, because thinking about it, if all your values were negative, then the the stacked order will change and the tooltip will look as you want. I need some time to think about this, I hope some one give us their opinion, I will add the "help wanted" tag in case some one wants to.

p.s.  I am color blind, your colors make it really hard for me :smile:

**Comment by camou23** [comment]
Then maybe we need a way to arange the ToolTip order manually?

**Comment by beto-rodriguez** [comment]
I think we can not change order of the tooltip by default, since this tooltip works for every series, and it will look strange in most cases. 

but as you suggested we could invert the order only for a specific case, like yours, I added an article a couple of days ago about it

http://lvcharts.net/App/examples/v1/wpf/Customizing%20Tooltips
