### ISSUE TITLE
Feature request: public function to get default stroke color by index before creating the series

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#217]
I am displaying my data in two different visual elements from which only one is LiveCharts. I would, however, like to use the automated colors for the LineSeries stroke of LiveCharts for consistent display in both elements.
Therefore it would be handy to know the colors of LineSeries in advance, before creating them.
Until now I am using LiveCharts.Wpf.Charts.Chart.Chart.Colors(_ValueIndex) or, since 0.7.3, LiveCharts.Wpf.Charts.Base.Chart.Colors(_ValueIndex) to return the color.
This, however, requires _ValueIndex to be within [...]Colors.Count. I could, of course, create a function on my own that cycles through this color array, but I think this function actally belongs to LiveCharts (and is already implemented).

Is that function publicly accessible?

Regards,
Pusaken

**Comment by beto-rodriguez** [comment]
The problem is that the functionLiveChart uses can only be called once, it increments an internal count so the colors do not repeat, but the function is really simple no need to cycle anything, try

    var mytargetSeries = new LineSeries();

    var myCollection = new SeriesCollection()
    {
         new LineSeries(),
         new LineSeries(),
         new LineSeries(),
         //and many more....
         
         myTargetSeries
    }

var seriesIndex = Chart.Colors.IndexOf(myTargetSeries);
var nextColor = Chart.Colors[seriesIndex%Chart.Colors.Count];
