### ISSUE TITLE
C#4.0 SUpport

### ISSUE THREAD

**Issue by TheCSharpCoder** [beto-rodriguez/Live-Charts#24]
Hello,

it would be great if the library will be supported in C# 4.0.

I changed lines like this one:
var labels = SecondaryAxis.Labels?.ToArray();

in that one:
var labels = SecondaryAxis.Labels != null ? SecondaryAxis.Labels.ToArray() : null;

and then it will compile and work unter C# 4.0

These are not much changes but a few.
Try to compile it with Visual C# 2010 Express for example and yu'll see it.

Regards

**Comment by beto-rodriguez** [comment]
Dll file is compiled for .net 4.0, 4.5, 4.5.1, 4.5.2 and 4.6 from this question http://stackoverflow.com/questions/247621/what-are-the-correct-version-numbers-for-c it should be enough to support c# 4. the problem is that I wrote those examples in c# 6, but if you install instead of clonining in visual studio 2010, install the nuget package you should not have any problem. Try it and let me now please. As far as i know everything should work fine if you use at least .net 4.0

**Comment by TheCSharpCoder** [comment]
Hello, 

Visual C# 2010 Express doesn't support the packages. 
I'll do the few changes in the source and that's ok for me. 

It was only a suggestion that your library source could be used by more people. 

Regards

**Comment by beto-rodriguez** [comment]
are you using .net 4?

**Comment by TheCSharpCoder** [comment]
Yes because of the compatibility to Windows XP.

**Comment by beto-rodriguez** [comment]
but you are you using .net 4 in your project? Go to SoluctionExplorer -> Properties -> Application -> then target framework should be at least 4. I think default in visual studio 2010 is 3.5

**Comment by TheCSharpCoder** [comment]
Yes it's set to 4.
But if you don't want to do the few changes it's ok for me. No problem. 

Am 7. Oktober 2015 15:58:40 MESZ, schrieb Alberto Rodriguez <notifications@github.com>:
