### ISSUE TITLE
Fixed scale of secondary axis won't work

### ISSUE THREAD

**Issue by TheCSharpCoder** [beto-rodriguez/Live-Charts#25]
Hello,

I hope this section here is the right one for such questions. I can't findy any other discussion possibility.

When I set the minimum and maximum of the secondary axis like the following, this axis won't be fixed:
LineChart.SecondaryAxis.MinValue = 0;
LineChart.SecondaryAxis.MaxValue = 1000;
A new added point will be drawn on the right even if I have only 100 points in the chart. I expected that the values will be shown between 0 and 100 of the secondary axis and not over the whole range from 0 to 1000.
What do I need to change to get this behaviour?

**Comment by beto-rodriguez** [comment]
What you need is a Scatter chart, the problem with line chart (as with bar and stacked bar) is that it does not scales on secondary axis. Why? just because they are designed to display same separation between Secondary axis points, if you need scale on both axis you need scatter chart. Hope it helps I wish you could do this question on stackoverflow so we can bring traffic to this library and with it help and contributors.
