### ISSUE TITLE
How to: Improving Rendering Performance?

### ISSUE THREAD

**Issue by MarioHsiao** [beto-rodriguez/Live-Charts#252]
When I binding  LineSeries with a very big data collection like  "Values = new ChartValues<double> { 1,2,3,4,5,6,7,8 .........20000 }" almost 20000 data, it display very slowly, how can I improve rendering performance?

**Comment by beto-rodriguez** [comment]
To improve performance right now you only can

* 1. Disable animations
* 2. remove extra shapes, with `Chart.Hoverable = false;` & `Chart.DataTooltip= null;` and ensure your chart has no dataclick event attached

Sadly that is all you can o right now, I already have tested some numeric algorithms to improve drastically performance, I have not update them to 0.7 because first we need a really stable library, we are really close.

0.5 version with high performance was able to plot 3,000,0000 points in 1 second, 0.7 is much faster normally it is 3-4 times faster, but I need to update the algos to 0.7 and I really hope it could draw 3 times more points with this improvements i have built, but I really don't think 0.7 will be able to plot 10 million in 1 second, I will be happy with 5 million, I don't know, I hope they surprise me with 0.7 :smile: 

This algorithms will sponsor the project, they will be really cheap compared with any other charting library, I am not sure about the price yet, but the idea is just to sponsor the project , pay the web site, update documentation and all that stuff that I think is the best to keep the project alive.

In my experience I have updated this algos many times, that I really want to wait for all the features to be ready before release them, since they depend on how LiveCharts works, I hope this month this algos are ready, I am trying to get everything ready asap!

**Comment by beto-rodriguez** [comment]
Already added a better article to solve this:

Please see https://lvcharts.net/App/examples/v1/wpf/Improve%20Performance

Some series are not ready yet, the site explains it better

Thanks!
