### ISSUE TITLE
zooming feature lost after changing chart visibility or location

### ISSUE THREAD

**Issue by Showmaster3000** [beto-rodriguez/Live-Charts#253]
When I change the visibility and/or location of a CartesianChart, the zooming feature is lost.
Start debugging project: zooming works fine
Change location and/or visibility: zooming doesn't work any longer
Close and restart debugging project: zooming works again
Just updated to the latest 0.7.6 today - and the problem still appears.

**Comment by beto-rodriguez** [comment]
Hello

I made some changes with zooming and panning to fix #270 

I this issue was directly related because I cant reproduce it any more, could you please try 0.7.11 (currently only available cloning the library, I will publish it in a couple of days)  and let me know if it is fixed for you?

here is how it looks for me now

![visibilityissue](https://cloud.githubusercontent.com/assets/10853349/17313642/01195bfe-5823-11e6-9f27-d5083b676613.gif)

**Comment by everystone** [comment]
Im having a similar issue. If I enable Zoom and:
1. load data from January, set axismax and axismin
2. clear the values, then load february and sets AxisMin and Axismax

The chart does not update and display the new values. I tried cloning and building the repo, but when I add reference to LiveCharts.dll from Bin/release Visual studio gives error "Referenced assembly 'LiveCharts, Version=0.7.11.0, Culture=neutral, PublicKeyToken=null' does not have a strong name"

Any advice?
Thanks

**Comment by beto-rodriguez** [comment]
You need to reference both, LiveCharts and LiveCharts.Wpf from the repo

**Comment by everystone** [comment]
I have added Live-Charts\WpfView\bin\Release\LiveCharts.dll and LiveCHarts.Wpf.dll,

**Comment by everystone** [comment]
Sorry, turned out I had to sign the assemblies.
On version 0.7.11 I still have the issue where updates to AxisMin and AxisMax are ignored after I Zoom or Pan the chart once.

**Comment by beto-rodriguez** [comment]
This issue seems to be fixed for me in 0.8

Feel free to add any feed back if it not working correctly for you
