### ISSUE TITLE
 data is too much or too fast refresh rate of data

### ISSUE THREAD

**Issue by SunArlen** [beto-rodriguez/Live-Charts#255]
When the data is too much or too fast refresh rate of data occurs when the "Collection was modified; enumeration operation may not execute", this is a BUG or to limit the data and refresh rate?

**Comment by beto-rodriguez** [comment]
How much is too fast?

Right now the updater is fired only every time animations finishes, in the next example I exmplain a bit how it works 

http://lvcharts.net/App/examples/v1/wpf/Constant%20Changes

**Comment by abraaocaldas** [comment]
I have the same issue, i update my data from another thread and sometimes it got too fast, like every 50ms, in this case the lvcharts crash.

**Comment by abraaocaldas** [comment]
I found the problem, on ChartValues Class -> Iterate method, I changed the this, to this.ToList(), fixed the problem for me, I know that is not the best workaround, but worked. #260

**Comment by abraaocaldas** [comment]
Hello, any news on this, the problem is still ocurring?
Because for me it´s not a problem anymore and I´m using a lot of charts at same time with refresh rate about 300ms...

**Comment by beto-rodriguez** [comment]
I actually was never able to reproduce this error, based on your comments it was fixed. I added the in progress label and reopened the issue because I am testing the performance in your workaround `.ToList()`, it does not have an important impact in performance in the next version (0.7.12) and brings more stability when working with async operations(based on your feedback)

**Comment by abraaocaldas** [comment]
Ok!, but If someone have the same problem again I can help to find a better way to fix it, if necessary.

**Comment by beto-rodriguez** [comment]
This helps as feedback for #336
