### ISSUE TITLE
Does Live-Charts support graph interaction palette? looks like use "Tools Panel" in "Blend for Visual Studio 2015".

### ISSUE THREAD

**Issue by MarioHsiao** [beto-rodriguez/Live-Charts#256]
We usually use "Tools Panel" in "Blend for Visual Studio 2015" to control the whole artboard like zoom and pan actions, like I said in this article, [Zoom or pan the artboard](https://msdn.microsoft.com/en-us/library/cc294501%28v=expression.40%29.aspx).

So, I mean, do you consider to implement this "Tools Panel" (include Zoom, Pan in it) with in LiveCharts?

We usually used to familiar with the operation like:
1. Pan: hold “Space” + mouse left drag.
2. Zoom: hold "Ctrl" + mouse wheel scrolling
3. Double-click "Pan" to center in view.
4. Double-click "Zoom" to zoom to actual size.

Related article: [Creating a UI by using Blend for Visual Studio](https://msdn.microsoft.com/en-us/library/jj171012.aspx)

**Comment by beto-rodriguez** [comment]
I will take a look at your info, thanks for the suggestion, I really appreciate them

**Comment by beto-rodriguez** [comment]
Ok I'll try to answer this after this long time I have a better idea of what the library needs and how to solve these cases, let met try to answer:

 > Pan: hold “Space” + mouse left drag.

The library pretends to be built in Xamarin/Uwp too, so this cant be included in the library by default, but the library makes it really easy for you to implement, notice all you need to do to Pan a chart is move the Axis.MinValue and Axis.MaxValue properties, as shown in this example where I do my own panning from code https://lvcharts.net/App/examples/v1/wpf/Data%20Pagination

 > Zoom: hold "Ctrl" + mouse wheel scrolling

Similar answer, I reccomend you implement it your self because of the mobile target of the library, all you need to zoom in/out is change the axis range, as I said in the previous point, zooming might see a but more complex, notice the Chart object also exposes this methods, so you can call it and let the library decide the new range of the axis, or built your own, here is the source code of the zooming, in case you want to build your own https://github.com/beto-rodriguez/Live-Charts/blob/master/Core/Charts/ChartCore.cs#L413

    Chart.Model.ZoomIn(new CorePoint(10, 10)); //the core point is the point in the chart where 
                                                                            //the zoom is centered

 > Double-click "Pan" to center in view & Double-click "Zoom" to zoom to actual size.

    You can easily reset the current zooming/Panning in the library setting the axis max/min limits to double.nan, as shown here :  https://github.com/beto-rodriguez/Live-Charts/blob/master/Examples/Wpf/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml.cs#L114 I just noticed this example is not linked to the web site, i'll do it asap and you will be able to see it the web site zooming article...


Please let me know if something is not clear, I am closing this for now.

Thanks for the beedback
