### ISSUE TITLE
Chart Legend (Point Color)

### ISSUE THREAD

**Issue by Billy-Joel** [beto-rodriguez/Live-Charts#271]
Hi Beto,

Good day, I'm trying to build a line graph without the line just the points. When I tried to show the legend, I see no point (shape) in it, just the title. So I tried to investigate and found out that the color and stroke of the shape in the legend are actually the color of the fill property and the thickness of the line stroke.

![capture](https://cloud.githubusercontent.com/assets/18839973/16938950/0e2d14e2-4d8e-11e6-80f3-0c09b1a5bb5a.PNG)

Will it be much better if we bind the color to the PointForeground property and not the fill?

What do you think?

Thank you very much.

Regards,
Billy Joel

**Comment by beto-rodriguez** [comment]
Hello Billy

You are right, this was wrong, last commit should fix it, but I will keep this issue open because, in this cases where you don't need a line, it is not recommended to use `LineSeries` the algorithm of a lin series is much more complex than `BubbleSeries` but the current implementation of `BubbleSeries` seems not enough to support this (custom points shapes)

So I will keep this issue open to remind me to fix:

1. Rename `BubbleSeries` to `ScatterSeries`, this will help users to understand that this series is more useful than what it seems, `BubbleSeries` draws points according to X,Y and weight, the size of every point scales according the weight of the point, but if you only pass X, Y coordinates all points will take the same size, I need to explain this better.
2. Add support to custom Point shapes to this series.

**Comment by Billy-Joel** [comment]
Yeah, I was thinking of the same thing but failed to mention it.
Renaming it to ScatterSeries will be a great idea.... :)

Thank you very much Beto for the reply... I'm loving this control more each day... :)

Regards,
Billy Joel

**Comment by beto-rodriguez** [comment]
This should be already supported correctly. this fix should improve the way every one using this library sees the `BubleSeries`, changes:

* `BubbleSeries` is now called `ScatterSeries`
* Renamed `BubbleSeries.MinBubbleDiameter` and `BubbleSeries.MaxBubbleDiameter` to `BubbleSeries.MinPointShapeDiameter` and `MaxPointShapeDiameter` to keep it consistent.

Here is an example:

    <lvc:CartesianChart LegendLocation="Right" Background="White">
            <lvc:CartesianChart.Series>
                <lvc:LineSeries Values="1,2,5,4" 
                                PointGeometry="{x:Static lvc:DefaultGeometries.Diamond}"
                                PointGeometrySize="20"
                                Fill="Transparent"
                                PointForeround="IndianRed"/>
                <lvc:StepLineSeries Values="3,2,5,6"
                                    PointGeometry="{x:Static lvc:DefaultGeometries.Square}"
                                    PointGeometrySize="20"
                                    Fill="Transparent"
                                    PointForeround="IndianRed"/>
                <lvc:ScatterSeries Values="2,1,3,4"
                                   PointGeometry="{x:Static lvc:DefaultGeometries.Trangle}"
                                   MinPointShapeDiameter="10"
                                   MaxPointShapeDiameter="35"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>

![untitled](https://cloud.githubusercontent.com/assets/10853349/17304563/d2bee922-57eb-11e6-83df-f7b7fa1bc5c7.png)
