### ISSUE TITLE
DataLabel Positioning

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#281]
Hi,

I would like to know if there is an option to set the DataLabel position. For example, the position of DataLabel is set to Top.

Right now, based on the bar chart value, my DataLabel is automatically set into the bar chart. Please see screenshot below:
![untitled](https://cloud.githubusercontent.com/assets/14113223/17164110/0f9e1878-53d6-11e6-8869-164380e8aa52.png)

Thanks

**Comment by beto-rodriguez** [comment]
Thanks Hishaamn, now by default Column and Row series have more space,  this was happening because the label needed to be placed outside the canvas, so the library decided to place it at bottom, currently if your max value was 56, the library max separator was placed at 60, with these changes now it should be 70, this will give the canvas more space to place all the labels correctly, also added the new property `LabelsPosition` to control where labels are placed:

![mergedlabels](https://cloud.githubusercontent.com/assets/10853349/17308783/49b81c8c-5801-11e6-8400-5e402ba8f03f.gif)

**Comment by hishaamn** [comment]
Thanks for the info :)
