### ISSUE TITLE
WPF Drawing area dimensions

### ISSUE THREAD

**Issue by emmanuelz** [beto-rodriguez/Live-Charts#290]
Hi,

I have updated from an older version and I am now facing a problem with the drawing area dimensions. It is either larger or narrower than the control area. See the following pictures, the effective drawing area is hightlighted in red. This problem did not exist in the previous version (<0.7)

With the width set as Auto, a white space appears on the right. You can also notice that the grid is slightly larger than the chart line.
![1](https://cloud.githubusercontent.com/assets/12900513/17343450/05de361a-58fe-11e6-95d5-ac2749f20864.png)

On this graph (same data as above), with a fixed width, the last points are drawn outside of the control.
![2](https://cloud.githubusercontent.com/assets/12900513/17343460/13a7efac-58fe-11e6-9057-1b1ac2f2bf46.png)

Did I miss something in the update ? Thanks for your help.

**Comment by beto-rodriguez** [comment]
Hello

Ok I see 2 different issues, I will enumerate them in the same order you posted your images:

*1. it seems that the axis X is rounding the limits incorrectly, this could be because DateTime.Ticks is of type long, and I think something unexpected is going out there, can I please know the range of your value in X? 

*2. Now by default the MinWidth property of a chart is 125px, I think your chart width is less than 125px and since I by default force this min limit then the chart is drawing bigger, please reduce the Chart.MinWidth property and let me know if this fixed the issue, I will reduce this min limits in a future version, this was introduced due depending on the container you are using charts could not being visible by default.

**Comment by emmanuelz** [comment]
1. The values on the X axis are in fact an array of strings. The labels array has the same size as the values array.
2. Ok, changing the MinWidth did the trick. Thanks !

**Comment by beto-rodriguez** [comment]
You were right, the Line Series by default was rounding, this is not the desired behavior, now it stretches to axis range.

**Comment by gjordanp** [comment]
Is there any way to make drawingMargin equial to chartWidth and Chart.Height
