### ISSUE TITLE
Live-charts in production? (question)

### ISSUE THREAD

**Issue by everystone** [beto-rodriguez/Live-Charts#324]
Hi,

Ive been using livecharts(wpf) in production software at work, and it works great. Im just curious about others thoughts, are you using it in production? is it adviced against in its current state?

Cheers

**Comment by beto-rodriguez** [comment]
Well the first version of this project started almost a year ago, but then I started dedicating more time to the project since february of this year, so we can say it is a new product, and as any other project you could face some issues.

But there are close to 240 issues reported and solved, the downloads have increased and
reports decreased, so that is a good sign.

I think the product is solid enough to be used in a production project, I am also using it, meanwhile you don't need a high performance chart (more than 200 points per chart)

Version 1.0 will be released when the library has a solution for high performance

**Comment by everystone** [comment]
I understand, thanks for answering.
