### ISSUE TITLE
Behavior change request for axis max limit

### ISSUE THREAD

**Issue by narfster** [beto-rodriguez/Live-Charts#341]
#### How to reproduce?

When you add a point to a chart, the point will be added at the edge of the chart. This seems to a user as if the point is cut at the edge. recommended behavior is that point will be added before edge of chart.
#### Extra notes

You could control your axis max limit to achieve same result, but should be as default.
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.14.3</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is now fixed and will be included since the next version of the library, the next image illustrates the fix, 
to the left the result we had, and to the right the fixed one, thanks for your report.

![untitled](https://cloud.githubusercontent.com/assets/10853349/21833278/aba051c2-d776-11e6-875f-df457cb6dd20.png)
