### ISSUE TITLE
Binding broken after assining value to myStelpLineCHart.AxisX[0].MaxValue

### ISSUE THREAD

**Issue by narfster** [beto-rodriguez/Live-Charts#343]
#### How to reproduce?
1. set up a binding to MaxValue proprty:

            <lvc:CartesianChart.AxisX/>
                <lvc:Axis Title="Time Stamp" 
                          LabelFormatter="{Binding XFormatterOccupencyAnalizedChart}"
                          MaxValue="{Binding AxisMax}"/>
            </lvc:CartesianChart.AxisX>

2. On each new chart point, update the corresponding property + 100ms ahead lets say.

3. see it works ok

4. setup a button / event that will change MaxValue or MinValue directly thru code.
OccupencyAnalyziedChart.AxisX[0].MinValue = somevalue

5. continue to update chart as in step 2.  see that binding is broken.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.14.3</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
I am not sure if I understood this correctly, but as I see it this is a normal behavior in WPF

When you assign a a value directly to any control property, the binding is lost, you are replacing it with a raw value.

So, instead of:
   
    OccupencyAnalyziedChart.AxisX[0].MaxValue = somevalue

Try:

    AxisMax = someValue;
   //Axis.Max must notify the change to work properly, implementing INotifyPropertyChanged

Let me know if this does not solve your issue.
