### ISSUE TITLE
Gauge and Chart Label customization Rotation

### ISSUE THREAD

**Issue by briggsyuk** [beto-rodriguez/Live-Charts#352]
Visual Feature Request:
- Ability to Rotate Labels on Gauges independently. This will allow the rotation of Gauge. 
- Ability to Hide "To", "From" labels on Gauge.
- Ability to Rotation of data Labels inside Chart Columns
- Ability to modify X,Y position of Data Labels positions on chart columns
- More default standard Datalabel dock positions such as Float on top, Left of Bar, Right of bar...

Off Topic but still vital i believe:
- Allow the guage to display multiple level gradients.
  ( Like this: http://previews.123rf.com/images/vectora/vectora1411/vectora141100102/33450513-Speedometer-or-general-gauge-dial-template-for-measuring-comparison-concepts-Vector-icon-Stock-Vector.jpg)

I believe these features will enhance the ability to use these in a more customisation way, particularly the gauge which i feel is very powerful but lacking in some visual customisation options.

Thank you in advance.
Briggsyuk

**Comment by Shujee** [comment]
Thumbs up for ability to Rotation of data Labels inside Chart Columns. We should at least be able to set rotation to 0 instead of default 270.

**Comment by beto-rodriguez** [comment]
Ok last commit fixes most of the thinks listed here.

About labels positioning in bar series, it was fixed in https://github.com/beto-rodriguez/Live-Charts/pull/410 check the link for more info, it is already included in the latest version of the library.

The web site article will be updated with a better example that shows the new capabilities and flexibility of the gauge control:

the sorce code of this image can be found [here](https://github.com/beto-rodriguez/Live-Charts/blob/develop/Examples/Wpf/Gauges/Gauge360.xaml) (it will be sin the site once merged to master)

![untitled](https://cloud.githubusercontent.com/assets/10853349/21946820/b86583b8-d9a7-11e6-9e3b-88983ba944fe.png)
