### ISSUE TITLE
LabelPoint interfere to the format string of ToolTip

### ISSUE THREAD

**Issue by FoggyFinder** [beto-rodriguez/Live-Charts#362]
If you set your display formatter that will lead to the fact that the message in the ToolTip would contain duplicate information.

Repro:

XAML:
```xml
        <lvc:PieChart 
            Series="{Binding SeriesCollection}">
        </lvc:PieChart>
```

F#:
```fsharp
open System
open FSharp.ViewModule

type Some<'a> = {Title:string; Value: 'a}

module Utils = 
    open LiveCharts.Wpf
    open LiveCharts
    open LiveCharts.Defaults

    let inline createPieSeries result = 
        let formatter = 
            fun (chartPoint:ChartPoint) -> 
                sprintf "%f (%s)" chartPoint.Y (chartPoint.Participation.ToString("P"))

        let pieSeries = PieSeries()

        pieSeries.Values <- 
            [| result.Value |> float |> ObservableValue |] |> ChartValues
        pieSeries.Title <- result.Title
        pieSeries.LabelPoint <- Func<ChartPoint, string>(formatter)
        pieSeries.DataLabels <- true

        pieSeries

    let inline toSeries some = 
        some
        |> Seq.map createPieSeries
        |> Seq.map box
        |> Seq.toArray
        |> fun series -> 
            SeriesCollection()
            |> fun sc -> sc.AddRange(series); sc

type MainViewModel() = 
    inherit ViewModelBase()    
    let rand = Random()
    let count = 4

    let someData = 
        [|0..count|]
        |> Array.map
            (fun v -> 
                {Title = sprintf "Some%i" v
                 Value = rand.Next 30})
        |> Utils.toSeries

    member __.SeriesCollection = someData
```

Result:
![1](https://cloud.githubusercontent.com/assets/16510738/19849804/c7fdc224-9f5d-11e6-94f0-ced908e95764.jpg)

**Comment by beto-rodriguez** [comment]
The current tooltip is designed to work for all the series, so it decides if it requires to show the percentage column, in this case, when you are using a pie series, it uses this column too, because normally that is what we would need.

Sadly I don't see a good way to solve this, I think the default tooltip should be smart enough to display the required data, and it currently is.

I think the best solution for you would be to create a custom tooltip, it is really easy and then you can force it to your needs.

https://lvcharts.net/App/examples/v1/wpf/Tooltips%20and%20Legends

Let me know if you have a better solution for this.
