### ISSUE TITLE
Exponential calculation time on FinancialSeries

### ISSUE THREAD

**Issue by PsykotropyK** [beto-rodriguez/Live-Charts#379]
Hello Beto-Rodriguez

It seems there are some heavy processing with exponential calculation time to plot financial data.

My code needs the following time to show the MainWindow and stop using the CPU. The code basically create a random financial serie and set all what is requested to plot the data. The difference in between the 2 simulations is whether or not I set the DataContext of my MainWindow

.count() | w/o DataContext | Process Memory | with DataContext | Process Memory
------------ | ------------- | ------------- | ------------- | -------------
50 | <1s | 38.2 | <1s | 41.4
100 | <1s | 38.4 | 1s| 44.1
250 | <1s |38.5 | 1.4s| 46.9
500 | <1s |38.2 | 2.2s|50.8
1.000 | <1s |38.1 | 4.7s|57.9
2.000 | <1s | 40.7 | 17.3s|71.5
5.000 | <1s | 44.2 | 120s|142.3
25.000 | 1.1s | 66.8 | killed after 10min | ~200

Note also that after the first minute the process memory usage curve start to become more volatile

#### How to reproduce?

Create a random serie of financial data (OhlcSerie or CandleSerie) and plot it

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
<tr>
    <td>Visual Studio</td>
    <td>Enterprise 2015</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi @PsykotropyK 

Yeah, the library gets slow when there are many points in the UI, this issue lead me to investigate and improve the performance of the library, the solution was an additional package Livecharts.Geared it is not spammed properly yet, because it is new and has some known issues, I keep working on it, but you can download it and install it from Nuget

https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips
https://lvcharts.net/App/examples/v1/wpf/Installing%20Geared
https://lvcharts.net/licensing/pricing

I having a cheap but paid high performance will boost the quality of the library, the price is nothing close to many charting libraries and it will help me to give a better support to everyone.

I will close this issue for now, feel free to add any feedback here or in any other new issue.

thanks again

**Comment by PsykotropyK** [comment]
Hi @beto-rodriguez 

Unfortunately my budget is going as up as 0 so I will keep with the initial package. I would have liked to access the faster library but regarding the time you seem to spend on this project I can't blame you to look for some retribution to the heavy amount of hour spent.

Good luck with it, you deserve some cash for the good work :)
