### ISSUE TITLE
Real time cartesianChart slow as points added

### ISSUE THREAD

**Issue by MCOrdermatic** [beto-rodriguez/Live-Charts#407]
#### How to reproduce?

Using the Constant Changes demo, my real time graph gets progressively slower as I add points. It becomes very noticeable once the point count reaches 500 or so. You can replicate by commenting line 88 of ConstantChanges.cs ( //if (ChartValues.Count > 30) ChartValues.RemoveAt(0); )

I placed timing in ChartValues.GetPoints and noticed that calls to GetPoints are about 500ms once the point count becomes high.

In my application, the visible chart area is small and only displays less than 100 points. The initial 100 points do not appear delayed while rendering. I would not expect this to be related to rendering. I would assume that the point list is clipped to the visible chart area (approximately the last 100 points) so that only 100 points are being smoothed and rendered.

#### Extra notes

My chart area can be adjusted with form size by the user. It is difficult to tell how many points will be required to 'fill' the current horizontal range (time). I cannot accurately determine how many points to remove from the ChartValues collection as form size is adjusted (i.e. culling to last X number of points). 

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8.0.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 Pro 1607 build 14393.10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi, thanks for the report, yeah, the library get slow when there are many points in the UI, this issue lead me to investigate and improve the performance of the library, the solution was a Livecharts.Geared it is not spammed properly yet, because it is new and has some known issues, I keep working on it, but you can download it and install it from Nuget

https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips
https://lvcharts.net/licensing/pricing
