### ISSUE TITLE
Renderization speed is too slow

### ISSUE THREAD

**Issue by gzapataw** [beto-rodriguez/Live-Charts#434]
*I think that this a great library but with "huge" datasets it gets too slow, i.e. the same data (5 line series, about 500 datapoints each one) plotted with OxyPlots is rendered almost instantly, with LVCharts it takes about 35 segs. Do you think that is there a way to get a faster renderization?*

**Comment by beto-rodriguez** [comment]
At the beginning, LiveCharts was designed to be only good looking and animated charts, I started this library when oxyploy was already popular and had more than 100k downloads, but I required something different.

Then many users started being aggressive with this beauty and slow library 😢, so I decided to give it a try and improve the performance of the library, the results are awesome, and I have not tested it but I am sure it is faster than oxyplot now.

But as you can notice Oxyplot is really good but at the same time I've noticed they take a long time to fix issues/respond if you have any problem, and that I am ok with that, considering it is free, I want LiveCharts to be a little better than that, so I decided to have a price in the high performance component of the library, it is not spammed properly because it has some known issues, I really hope this week you will be able to find it easier in the site, and this repository.

The price is really low compared practically all charting libraries, again, I just want to keep the project alive, and I am not sure about the numbers but many users that have tried them have reported me to be one of the fastest out there.

I hope this answers your questions, you can donwnload an exmaple application using LiveCharts.Geared here https://lvcharts.net/content/exampleapp.zip, you can also get more info about it here https://lvcharts.net/licensing/pricing, I appreciate any opinion.
