### ISSUE TITLE
cartesianChart AxisX Separator with System.DateTime

### ISSUE THREAD

**Issue by Pulpino** [beto-rodriguez/Live-Charts#449]
#### How to reproduce?

There is an offset in Separator in the cartesianChart when using DateTime as AxisX.
I define:
                LabelFormatter = value => new System.DateTime((long)value).ToString("HH:mm"),
                Separator = new Separator
                {
                    Step = TimeSpan.FromHours(1).Ticks,
                }
            });
            cartesianChart.AxisX[0].MaxValue = DateTime.Parse("31/01/2017 16:00").Ticks;
            cartesianChart.AxisX[0].MinValue = (DateTime.Parse("31/01/2017 16:00").Ticks - TimeSpan.FromHours(8).Ticks);

And I obtain the graph below:

![image](https://cloud.githubusercontent.com/assets/25491528/22526292/f52f7b96-e8ca-11e6-86e0-6b7999a77ba2.png)

Separators are XX:10 insteed XX:00.

Thanks by advance for your help.

Best regards,

Thomas

#### Extra notes

Everything's running fine with version 0.7.11

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>NET 4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thanks for the report, the solution for this is a bit complex.... I'll try to find the best way to fix this, for now please force the formatter 😟 

    LabelFormatter = value => new System.DateTime((long)value).ToString("HH:00"),

**Comment by Pulpino** [comment]
Thanks for your feedback! Waiting for the fix, I will use the old version 0.7.11, because if I force the formater I have always the offset on the separator and I need to have the right hour at the right place.

Thanks also for all the work done for this wonderful library!

**Comment by beto-rodriguez** [comment]
From 0.9.3 and above you can let the Axis know the unit of your chart, so it can make better depositions to place separators, specifying the unit also improves the rendering for some cases, I'll explain the cases where you need to let the axis know the unit you are plotting in the web site, using date time type is one case, you could for example set the unit to hours, milliseconds, seconds etc...

var unit = TimeSpan.FromSeconds(1);

<lvc:Axis Unit="{Binding unit}" />

The correct behavior in 0.7.x is just luck, and there is no warranty that it will work for all cases.

**Comment by beto-rodriguez** [comment]
This solution caused new issues ( #460 #464 ), I rolled back and reopened...

**Comment by beto-rodriguez** [comment]
This is already fixed and will be included since 0.9.4, thanks for the report, the best solution I can think of, is to let the axis know the unit you are displaying, in this case seconds.

Since 0.9.4 if you don't set the `Axis.Unit` property, then the axis will try to guess, in some cases it could result in a wrong labeling, when you set the Unit then the axis will force the rounding of its labels to a multiple number of your unit.

It is much simpler that how it sounds:

    AxisUnit = TimeSpan.TicksPerSecond;

    <lvc:CartesianChart.AxisX>
      <lvc:Axis Unit="{Binding AxisUnit}">
    </lvc:CartesianChart.AxisX>

**Comment by FaTaOwita** [comment]
Hello Alberto,

just wanted to mention that I tried the latest version of LiveCharts and the latest version of the example "Constant Changes". There is still the issue, that the x-axis time-labels and separators are sliding to the left, instead of standing still and only change their values, like in the example-gif. 
Very likely this is a separated issue, but since you said that it could be related to this issue, I wanted to inform you.

Constant-Changes Original - x-axis time-labels standing still:
![constantchangesoriginal](https://cloud.githubusercontent.com/assets/26007399/23747004/67a4174a-04be-11e7-832a-77fef0812944.gif)

Constant-Changes latest version - x-axis time-labels sliding to the left:
![constantchangeslabelissue](https://cloud.githubusercontent.com/assets/26007399/23747025/8035d8ac-04be-11e7-894e-4a6a4cbf8493.gif)

Best Regards
Fabian T.

**Comment by gc9n** [comment]
Hey hello congratulations or the work you done , i just found this awsome tool , and i am trying to push data into a CartesianChart1 from a thread , 
So what i want is to parse 2 values  , instead of time and a value , that your example have.
I want X axis to have values from 1 to 100 and Z axis from 300 to 1500 , is that possible?
I have changed the Public Class MeasureModel to accept 2 double values

but in that point
CartesianChart1.AxisX(0).MaxValue = Now.Ticks + TimeSpan.FromSeconds(1).Ticks 
CartesianChart1.AxisX(0).MinValue = Now.Ticks - TimeSpan.FromSeconds(8).Ticks 

when i change it to this
CartesianChart1.AxisX(0).MaxValue = 1500 
CartesianChart1.AxisX(0).MinValue = 300 

i get the followin error
Additional information: One axis has an invalid range, it is or it is tends to zero, please ensure your axis has a valid range

OK its obviosly that something is wrong with z axis lables , if you can help me , it will be awsome

**Comment by GMoney349** [comment]
Hello,
I’m using version 0.97 of LiveCharts, and I want my X-axis time labels to ‘slide’ along the axis as new values are added to the series.  I see the comment from FaTaOwita above… I want my chart to do what its doing in the 2nd or 3rd GIF (X axis time labels sliding to the left).  I don’t want it to do what its doing in the 1st (X axis time labels standing still).  Is there a way to do this in 0.97?

**Comment by GMoney349** [comment]
> Hello,
> I’m using version 0.97 of LiveCharts, and I want my X-axis time labels to ‘slide’ along the axis as new values are added to the series. I see the comment from FaTaOwita above… I want my chart to do what its doing in the 2nd or 3rd GIF (X axis time labels sliding to the left). I don’t want it to do what its doing in the 1st (X axis time labels standing still). Is there a way to do this in 0.97?

I think I figured it out.  I had 'AxisStep' and 'AxisUnit' set to '1 second'.  Changing these to something larger (i.e. 30 seconds) makes the chart do what I want now.  The x-axis labels 'scroll' along to the left.

**Comment by Jonny5566** [comment]
@GMoney349 May I know got any method to resolve the issue which has been faced by @FaTaOwita ? Currently I'm facing the same issue as FaTaQwita.
