### ISSUE TITLE
Activator Key

### ISSUE THREAD

**Issue by arifaarish** [beto-rodriguez/Live-Charts#470]
*I have purchased the LiveCharts license but not able to find the Activation Key *

#### Extra notes

*Explain what you expect, feedback, images or anything you consider necessary*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*your Live-Charts version here*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*your .net version here*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*your windows version here*</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
I am really sorry for this, please to get your activation code you must: login in the site, here is the link lvcharts.net/licensing/manage then access your invoice to get the activator download link.

Once you downloaded the activator, please run it, your key will be shown in your browser, then insert this key in the activator.

The site is about to be updated to explain this better, if you face any issue just let me know I'll help you.

**Comment by beto-rodriguez** [comment]
Hello

I am closing this issue since the site was just updated and now it is more friendly to manage your licenses.

Please take a read to https://lvcharts.net/licensing/howto you should receive a mail soon notifying that managing licensing is easier now and has a lot of new features.

Let me know if you face any other issue. btw I am aware of the second issue you are facing with the activator as I'll let you know once it is fixed.
