### ISSUE TITLE
StackedColumns with multiple axes

### ISSUE THREAD

**Issue by danilosouza** [beto-rodriguez/Live-Charts#480]
#### How to reproduce?

When using multiple axes with StackedColumns, the chart won't separate the different labels according to the axes, even though theay are declared in the xaml file, instead the chart combines everything in one of the axes, as if it ignores the ScalesAtY parameter.

#### Extra notes

The chart should display tow stacked columns side by side for each label, scaled to their correspondig axes

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 Professional</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This works indeed, it seems that it doesn't because a column is over the second one, check out this sample:

```xml
<lvc:CartesianChart>
            <lvc:CartesianChart.Series>
                <lvc:StackedColumnSeries Values="1,6,3,8" MaxColumnWidth="999"></lvc:StackedColumnSeries>
                <lvc:StackedColumnSeries Values="6,2,9,4" MaxColumnWidth="999"></lvc:StackedColumnSeries>
                
                <lvc:StackedColumnSeries Values="2,6,3,5" ScalesYAt="1" ></lvc:StackedColumnSeries>
                <lvc:StackedColumnSeries Values="6,3,5,6" ScalesYAt="1" ></lvc:StackedColumnSeries>
            </lvc:CartesianChart.Series>
            <lvc:CartesianChart.AxisY>
                <lvc:Axis></lvc:Axis>
                <lvc:Axis></lvc:Axis>
            </lvc:CartesianChart.AxisY>
       </lvc:CartesianChart>
```

and the result:

![untitled](https://cloud.githubusercontent.com/assets/10853349/23828894/1122215c-06a6-11e7-9c5b-271b669b5d90.png)

I am closing this, since this works, maybe you need a different plot for this case, feel free to open a request with what you need.

Thanks for the report
