### ISSUE TITLE
Cannot effectively over-ride GetPointView

### ISSUE THREAD

**Issue by JoolzCheat** [beto-rodriguez/Live-Charts#500]
#### Issue

*I want to slightly change the design of the <b>CandleSeries</b> display. I have extended the class, and can override <b>GetPointView</b>, however I cannot cast to <b>CandlePointView</b> in order to expose the <I>HighToLowLine</I>, etc because <b>CandlePointView</b> is set as "Internal", and as such these protected properties are not exposed outside of the assembly.*

#### Solution

*Propose that <b>CandlePointView</b> (and other PointView classes) are instead changed to <b>Internal Protected</b> to allow people to extend/change the visual design outside of the LiveCharts binary*

**Comment by beto-rodriguez** [comment]
500 issues 🎉 😄 

Yeah I agree, there is no a single reason for this to be internal, I'll make them public in next release

**Comment by JoolzCheat** [comment]
Super fast response. Thanks a lot 👍

**Comment by beto-rodriguez** [comment]
I'll close this, with 0.9.6  we have more options, I don't think all the point views should be public, it does not feels clean.

This request was about supporting advanced coloring rules for financial series, they are already supported since LiveCharts 0.9.6 and LiveCharts.Geared 1.2.8

An article will include a sample in the site soon, here is a short sample:

```
public partial class MainWindow
    {
        public ChartValues<double> ChartValues { get; set; }
        public List<FinancialColoringRule> Rules { get; set; }

        public MainWindow()
        {
            InitializeComponent();

            Rules = new List<FinancialColoringRule>
            {
                new FinancialColoringRule(
                    (currentPoint, priorPoint) => currentPoint.Low > priorPoint.Low, Brushes.Red, Brushes.Red),
                new FinancialColoringRule(
                    (currentPoint, priorPoint) => currentPoint.High > priorPoint.High, Brushes.Blue, Brushes.Blue),
                //any other custom rule...
            };
            
            DataContext = this;
        }
    }
```

```
<lvc:CartesianChart LegendLocation="None">
            <lvc:CartesianChart.Series>
                <lvc:CandleSeries Values="{Binding ChartValues}"  ColoringRules="{Binding }"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
```

To override these objects, I would instead fork the repo and edit the source code, considering that 0.9.6 exposes now the sign files, you can easily do your own build and at the same time use the geared package.

**Comment by beto-rodriguez** [comment]
I'll close this, with 0.9.6  we have more options, I don't think all the point views should be public, it does not feels clean.

This request was about supporting advanced coloring rules for financial series, they are already supported since LiveCharts 0.9.6 and LiveCharts.Geared 1.2.8

An article will include a sample in the site soon, here is a short sample:

```
public partial class MainWindow
    {
        public ChartValues<double> ChartValues { get; set; }
        public List<FinancialColoringRule> Rules { get; set; }

        public MainWindow()
        {
            InitializeComponent();

            Rules = new List<FinancialColoringRule>
            {
                new FinancialColoringRule(
                    (currentPoint, priorPoint) => currentPoint.Low > priorPoint.Low, Brushes.Red, Brushes.Red),
                new FinancialColoringRule(
                    (currentPoint, priorPoint) => currentPoint.High > priorPoint.High, Brushes.Blue, Brushes.Blue),
                //any other custom rule...
            };
            
            DataContext = this;
        }
    }
```

```
<lvc:CartesianChart LegendLocation="None">
            <lvc:CartesianChart.Series>
                <lvc:CandleSeries Values="{Binding ChartValues}"  ColoringRules="{Binding }"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
```

To override these objects, I would instead fork the repo and edit the source code, considering that 0.9.6 exposes now the sign files, you can easily do your own build and at the same time use the geared package.

P.D. sorry for the late reply 😟
