### ISSUE TITLE
UWP: ColumnSeries not displayed

### ISSUE THREAD

**Issue by ach00** [beto-rodriguez/Live-Charts#501]
Hi,
I'am not able to make ColumnSeries work properly on UWP, I get no error but nothing is being displayed.

Also, is it possible to use the "Fill" property on StepLineSeries to make it look like a ColumnSeries?

Thank you in advance,

**Comment by beto-rodriguez** [comment]
Hello, sorry UWP for now is in a experimental phase, once WPF 1.0 is published UWP will have more love.

I am sure the latest UWP Nuget package works, it is version 0.8, now WPF latest is 0.9.5, many things have happened since the last UWP published package, I've updated UWP but without debugging the code, so there could be small issues, I'll be back to UWP soon.

I am closing this for now, you will soon (1 month maybe) see a newer version of UWP in Nuget.

**Comment by ach00** [comment]
Thank you for your quick response.
However I am not able to make the Fill property work on StepLineSeries, even on v0.8.0 nuget package.
Do you have any tips or workaround I could use to fix it? Maybe derive from your StepLineSeries class?

Thanks
