### ISSUE TITLE
Left White Space

### ISSUE THREAD

**Issue by Clarke937** [beto-rodriguez/Live-Charts#518]
**Left White Space in CartesianCharts**
![issue](https://cloud.githubusercontent.com/assets/12832931/24717129/a01e1aa4-19ee-11e7-9388-93e3051cff48.PNG)

Hi, I have a problem with the graphs of LineSeries and StackAreaSeries, and what happens is that I have a menu to change the type of graph for example from ColumnSeries to LineSeries, and when this is done, leave a blank space to the left and do not Displays the final part of the right. How could I solve it? Note: It only happens with these two graphs, with StepLineSeries and ColumnSeries does not leave this space.

**Comment by beto-rodriguez** [comment]
Hi

This is caused because the axis sets its own limits when you don't define them.

But a column series was an "Axis unit" of 1 while a line series is 0, maybe this link explains a bit http://stackoverflow.com/questions/38731985/how-customize-column-width-in-column-series

Soon docs will explain this concept better, for now forcing an update should do the job.

Try cleaning the axis limits (from https://lvcharts.net/App/examples/v1/wpf/Zooming%20and%20panning)

    //Use the axis MinValue/MaxValue properties to specify the values to display.
            //use double.Nan to clear it.
 
            X.MinValue = double.NaN;
            X.MaxValue = double.NaN;
            Y.MinValue = double.NaN;
            Y.MaxValue = double.NaN;

**Comment by Clarke937** [comment]
Ok try to clean them as you say but still nothing, thanks for replying anyway.
