### ISSUE TITLE
Axis Labels binding not raising when property changes (Lazy Data)

### ISSUE THREAD

**Issue by g1ga** [beto-rodriguez/Live-Charts#54]

**Comment by beto-rodriguez** [comment]
Hello, thanks  for reporting, you are right even it is a dependency property it won't update becase the text in that TextBlock is not binded to this property (I forgot).

**Comment by beto-rodriguez** [comment]
This should solve this issue, I have to say that I didn't test it, if it does not works please let me know.

Thanks again!

**Comment by g1ga** [comment]
Thank you for the prompt response, although I was referring to the property Chart.SecondaryAxis.Labels, not the Title. Thanks.

**Comment by beto-rodriguez** [comment]
I really don´t know what to say I have been thinking about this and I am not sure yet. I can´t see why this is needed. I would like to know a bit about what you are doing and why do you need this.
I just updated the code (https://github.com/beto-rodriguez/Live-Charts/commit/e9e1892252477f89e80bcdaf3dbdc5eb34f75c10) so now you can force a redraw without animating the chart, meanwhile you can call this method when your labels change.

```
chart.ClearAndPlot(false);
```

**Comment by g1ga** [comment]
In a MVVM context, direct access to the chart (the view), would mean to break the pattern... I'm attaching a demo project with the expected behavior. thank you.
[LC_Demo.zip](https://github.com/beto-rodriguez/Live-Charts/files/67567/LC_Demo.zip)

**Comment by beto-rodriguez** [comment]
I merged your project so we can fix this, it is called LazyData, I already fix some important bugs, sadly I have not found why Labels are not updating, as far as I see Axis.Labels is a Dependency property and should update when you change your model since you are implementing INotifyPropertyChanged, but it does not. Do you have any clue why? 

P.S. I also added a solution meanwhile we fix this, I know it brakes Mvvm but it’s just while we found the issue. 

@gregsdennis I know you know the answer for this can you please help us here?

the labels should print if we remove this line 
https://github.com/beto-rodriguez/Live-Charts/blob/master/LazyData/MainWindow.xaml.cs#L41

**Comment by gregsdennis** [comment]
Sure, I'll take a look at it later tonight.

**Comment by gregsdennis** [comment]
That line definitely need to be removed.  It's overriding the binding that's set in XAML.

@g1ga, if you set the property on the view model to be an `ObservableCollection<T>`, you don't need to set it again each time.  Instead just update the contents of the existing collection.  WPF will update the view as the collection changes.

@beto-rodriguez, the `Labels` DP in `Axis` has a dummy callback.  I think this may prevent the labels from being updated in the UI.  In an ordinary WPF app, this wouldn't be the case, but this library is a special case since you're redrawing the UI.  I think you're going to have to do that non-animated refresh you mentioned when this property receives a new value.

Let me know if that works for you guys.

**Comment by beto-rodriguez** [comment]
Thanks @gregsdennis I will take a look at what you said

**Comment by mgth** [comment]
I just find it happened to me when first label is empty, cause GetLabelSize function then report 0

**Comment by beto-rodriguez** [comment]
This should be fixed now with https://github.com/beto-rodriguez/Live-Charts/commit/ed5b5d6e8e6c00eb5169b95bfb86ebde4b628c92 the problem was actually really simple, PrimaryAxis and SecondaryAxis were not added in the chart visual tree, so when you wanted to run that binding, the DataContext was null all the time for Axis.Labels, I just pulled both inside the chart canvas, right now I am fixing some others new issues but this should solve this 100%, please let me know if it does not.

**Comment by beto-rodriguez** [comment]
Ok, after some undesired bugs, bindings and Mvvm should now work much better, I fixed many bugs, I also added a "complex" Mvvm example so we can always test this in future versions

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/Line%20Examples/LazyDataLine.xaml.cs

Also for simple charts you will need to change a little bit the sintax. for more info go to

https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.5.9
