### ISSUE TITLE
Serie incorrect reference all over.

### ISSUE THREAD

**Issue by b1u3w01f** [beto-rodriguez/Live-Charts#61]
Am I missing something or does the project repeatedly refer to 'Serie' for chart types when the correct reference is Series; including for BarSeries, PieSeries, etc? This error seems to be right across the code and documentation.

**Comment by beto-rodriguez** [comment]
In documentation maybe, since this project is in a beta version, names and name spaces have changed since first version, but most of the changed are documented here https://github.com/beto-rodriguez/Live-Charts/releases, 

can you please point where this code refers to Serie instead of Series? this should be a bug, but I dont see where it happens.

Thanks

**Comment by beto-rodriguez** [comment]
Already added a note here https://github.com/beto-rodriguez/Live-Charts#installation 
please let me know if this works for you

**Comment by b1u3w01f** [comment]
Yeah I was incorrect in my writing, its just the documentation and examples. 

Appreciated it was likely just due to fast iterations and a small changed being picked up, just thought I should point it out incase you hadnt seen it / for anyone else that didn't realise the issue when they were trying to follow the examples.

Great work though and the example on #installation page is great.

**Comment by beto-rodriguez** [comment]
@b1u3w01f I am updating documentation because I just did an important update, thanks for reporting I  will now link to the current example in code, so it is always up to date in docuemtation.
