### ISSUE TITLE
public PlotArea

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/Live-Charts#62]
Hi,

I need to draw things in the background of the plot area at precise position. For now I just modified source code to get access to PlotArea, but I would not want to modifie source code.

Maybe Chart object could provide a background canvas to draw on, or is their a better way already present.

Ps : Is there a better place to discus about Live Chart (forum, etc) or is this the place to ?

**Comment by beto-rodriguez** [comment]
please see 

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/Line%20Examples/UiElementsLine.xaml.cs

Plot are is privite but LiveChart lets you get the the current Canvas.

By now this is the way to discuss about LiveCharts, you can try StackoOverflow but since this is a new project maybe I will be the one anwering your question

**Comment by beto-rodriguez** [comment]
please let me know if this solves your issue.

**Comment by mgth** [comment]
Nice, that's what I need, thank you very much.
