### ISSUE TITLE
Lines Don't Represent the Data Accurately

### ISSUE THREAD

**Issue by marcruch** [beto-rodriguez/Live-Charts#642]
#### How to reproduce?

Lines that should be horizontal or vertical are sometimes rendered at a slant, as if data points are being skipped. For example:
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Forms;

using LiveCharts;
using LiveCharts.Defaults;
using LiveCharts.Wpf;
using LiveCharts.WinForms;
using LiveCharts.Geared;

namespace LiveChartsDemo
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            var l = new List<DateTimePoint>();

            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 0, 1, 0), 0));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 0, 1, 1), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 0, 2, 0), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 0, 2, 1), 0));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 1, 1, 0), 0));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 1, 1, 1), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 1, 2, 0), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 1, 2, 1), 0));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 2, 1, 0), 0));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 2, 1, 1), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 2, 2, 0), 100));
            l.Add(new DateTimePoint(new DateTime(2000, 1, 1, 2, 2, 1), 0));

            GearedValues<DateTimePoint> vals = l.AsGearedValues().WithQuality(Quality.Highest);

            cartesianChart1.Series.Add(new GLineSeries
            {
                Values = vals,
                LineSmoothness = 0,
                PointGeometry = null
            });
        }
    }
}
```

![livechartsdemo](https://user-images.githubusercontent.com/31834744/31209219-c8e3c0d2-a946-11e7-9bac-7644d981556d.png)

#### Extra notes

The desired effect is to indicate data points of some given values for some given durations and to do it in a manner that is visually accurate over different time scales. This is close... but it doesn't quite seem to work.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7 (Geared: 1.2.8.2)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is caused due the `Geared ` package virtualization, in this case you are using `DateTime` type, the library will use the `DateTime.Ticks` property, to generate the X coordinate of your plot, this means that the difference between each point is extremely small, since the precision you are passing is seconds.

This is a precision issue, the library will behave much better if you help it, some alternatives I can think of are:

1. Use a more suitable presicion

Since you are currently using `DateTime` type, and you want a seconds precision, you are probably not using the best unit inf your case, instead you could use a int value as you X coordinate, that represents seconds.

i.e:

           l.Add(new Point(0, 0));  // Second 0, Value 0

2. Don't use the geared package for this case.

I know it sound bad, but the geared package is designed to work with many points, it virtualizes the data, this means that the data is loaded according to many factors such as the current user zoom, the number of points and the type of series, in this case where you are only plotting a few points, separated by a really short interval (due `DateTime.Tick` property) then this virtualization is confusing you. 

I hope this helps.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
