### ISSUE TITLE
How to show moving lines to track the coordinates of the mouse

### ISSUE THREAD

**Issue by wangk99** [beto-rodriguez/Live-Charts#662]
Hi, @beto-rodriguez, 
  I'm working on a standard stock chart
![untitled](https://user-images.githubusercontent.com/10994705/31972587-066ac810-b8e7-11e7-9324-ca2d36a33217.jpg)
.  When I hover the mouse around the chart, do you know how to show the vertical and horizontal lines that track the mouse position and show the values on the X and Y axis?  I'm sure you have seen it in many stock charts.  Please see the attached screen shot.  The mouse is around the center of the chart, it shows two doted lines that moves with the mouse and show the values in the black boxes on the x and y axis.
  Thanks.

Yizhong

**Comment by wangk99** [comment]
Btw, i bought 3 of your Geared licenses a few days back and I really hope this works.

**Comment by wangk99** [comment]
Another question, is it possible to draw a line on a chart by mouse click, drag, and release?

**Comment by beto-rodriguez** [comment]
Hi

Check out [this sample](https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/SectionsMouseMove):

Notice the Y axis, sticks to the mouse position, while the X axis snaps to the closest point.

![](https://cloud.githubusercontent.com/assets/10853349/25369615/d8ed8f3e-294a-11e7-82c4-b1200059525c.gif)

Currently there is no a built in way to add a line when you click your chart, but you can add a new line series or a section (if you need a straight line) according to the mouse position, in both cases you have to build it.

I am closing this issue, since I think I answered all of your questions, feel free to reply this or create any other issue.

**Comment by wangk99** [comment]
@beto-rodriguez Thanks, AlBerto, looking at the animation picture, the coordination grid lines are exactly what I need.  I'll try your examples, and try to figure out using a section to draw a straight line.

**Comment by imran2say** [comment]
Can we do this on Winform? @beto-rodriguez

**Comment by liliangsen** [comment]
May I ask if this function can be implemented on Avalonia

**Comment by beto-rodriguez** [comment]
try LiveCharts2 https://github.com/beto-rodriguez/LiveCharts2
