### ISSUE TITLE
StrokeThickness issue on line charts

### ISSUE THREAD

**Issue by emmanuelz** [beto-rodriguez/Live-Charts#69]
Hi,

Using a StrokeThickness < 3 on line charts makes the line being not rendered completely or being interrupted.

See the screenshot, red line has a stroke thickness of 2, blue line of 1.

![stroke](https://cloud.githubusercontent.com/assets/12900513/12373804/dbbe90e6-bc86-11e5-9682-b702da2b00c8.png)

**Comment by beto-rodriguez** [comment]
Thaknks for reporting will fix as soon as possible.

**Comment by beto-rodriguez** [comment]
This happens because this is kind of a complex math calculation, If I fix this I will actually just make a better aproximation I just added the help wanted label, it would be awesome if some one could solve this in a better way.

https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Series/LineSeries.cs#L130

**Comment by emmanuelz** [comment]
Thanks for your answer.

Note that the problem is only visible with lower values, wich means that the approximation you make is not the only factor.
It seems that the whole Stroke is scaled by the thickness factor, so you will have somewhere to scale the computed length : l = l / StrokeThickness.

Here is some code that should make a better approximation.

[LineSeries.zip](https://github.com/beto-rodriguez/Live-Charts/files/98075/LineSeries.zip)

**Comment by beto-rodriguez** [comment]
Awesome Thanks very much for sharing your code
