### ISSUE TITLE
Please include nuget script

### ISSUE THREAD

**Issue by xanth** [beto-rodriguez/Live-Charts#71]
We have a local nuget repository for our dependencies and as such would like to deploy Live-Charts from it, so I was wondering if with the next version could release your nuget script.

**Comment by beto-rodriguez** [comment]
Sorry I am afraid I dont understand this

**Comment by xanth** [comment]
Are you able to share the script that you use to deploy to nuget?

**Comment by beto-rodriguez** [comment]
I don't use any script, I just follow these steps https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by gregsdennis** [comment]
@xanth, what is your purpose with the script?  You should just be able to download the package directly from nuget.org and upload into your private repo.

Secondarily, while I understand that I don't know your processes and policies, I would suggest that you just download Live-Charts from nuget.org directly into your solution.  If you have concerns about compatibility with future versions, just mitigate upgrading the package.  We tried duplicating public packages in our private repository also, and we found that it just causes other issues that weren't worth it.

**Comment by xanth** [comment]
We have had great success with our local nuget repository, having dependencies in the solution adds to commit noise. When I have time I'll write a nuget script to automate the process both for this and for our own solution. Again thanks @beto-rodriguez for your time.

**Comment by gregsdennis** [comment]
Just to be clear, we still have our local repo, but we only put libraries we create in it.  Libraries that are publicly available we get from those public sources.  This has worked well for us because it allows us to easily update them without having to migrate the updated packages into our repo.

Even so, whatever works for you.

In my open source stuff, I build my Nuget packages manually also.  I like the finer control over build numbers rather than it incrementing each time I actually build the solution.

**Comment by xanth** [comment]
You don't need to have versioning a la chrome if you don't want, just use a command line application to automate the process rather than having to edit the files each time. It's important that new dependencies are vetted prior to use so using our internal nuget repository is important as it formalizes the process.
