### ISSUE TITLE
pie chart Legends

### ISSUE THREAD

**Issue by IGNATIUSLIJO** [beto-rodriguez/Live-Charts#88]
https://github.com/beto-rodriguez/Live-Charts/blob/fdb16df2b6bb079cef7285174cda9eda4934f7bb/LiveChartsCore/Charts/PieChart.cs#L187

please check the above line this will fail always. This will make Legend colour will be default colour always

**Comment by beto-rodriguez** [comment]
This helps to solve #87 I will close this issue and merge it with #87 since both are related,
for 0.6.5 I will do a full review of pie chart. this will be concider for 0.6.7

**Comment by IGNATIUSLIJO** [comment]
instead of greater than i tried less than symbol . It worked fine with that change... Is it a correct way?

**Comment by beto-rodriguez** [comment]
@IGNATIUSLIJO  That line means: 

`c#
//if brushes is not null and there is a brush for this index (no it should be fine with less than)
series.Brushes != null && index > series.Brushes.Length
? series.Brushes[index] //then get a brush from brusher array
: new SolidColorBrush(series.GetColorByIndex(index)) //else buld a new one with default colors
`
For now instead of the syntax you used in #87 I woudl use the one in included examples, that is the one tested, pleas see https://github.com/beto-rodriguez/Live-Charts/blob/master/WPFExamples/Pie%20Examples/Custom/CustomPie.xaml

It should work the way you are trying but I am not sure why it is failing, I need some time to test and debbug it.

**Comment by IGNATIUSLIJO** [comment]
In my case i have 2 factors for pie chart. 

if first factor is less than 2 and second factor is minus of 2 then one set of colour 

if first factor is greater than 2 and less than 5 ,second factor will be 0 . then one colour

if first factor is greater than 5  ,second factor will be 0 . then one colour


that is why i want to control brush from code base


in #88 

`//index value is starting from 0 so index will always fail so it ll always go for SolidColorBrush 
series.Brushes != null && index > series.Brushes.Length
? series.Brushes[index] //then get a brush from brusher array
: new SolidColorBrush(series.GetColorByIndex(index)) //else buld a new one with default colors`

is my understanding is correct ?

**Comment by beto-rodriguez** [comment]
@IGNATIUSLIJO I think you are, here in my city I am just waking up, let me get a cofee and then we can talk :)

**Comment by IGNATIUSLIJO** [comment]
ya sure. Have a nice day :+1:
