### ISSUE TITLE
Support for print and zoom

### ISSUE THREAD

**Issue by NessfertIndia** [beto-rodriguez/Live-Charts#90]
Can we use print functionality  and zoom functionality with graph control 
Also is any chance to do dynamic drilldown of graph [ ie on clicking on a specific area view detailed information from graph]

**Comment by beto-rodriguez** [comment]
This library is ready for zooming, actually last release I made some important updates to zooming logic, https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.6.4 

This link should contain a example of zooming https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/HighPerformance it works but it might change in the next releases, because I need to make some improvements to HighPerformance charts, and zooming is directly related.

I think I will also include drilldown in the HighPerformance package, I will let you know when is ready my objective is to have everything working in the next weak.

**Comment by beto-rodriguez** [comment]
about the printing it is kind of easy to print a WPF control, but I guess I can add a shortcut.

**Comment by gregsdennis** [comment]
@beto-rodriguez, I would like to add that printing seems to be an application concern, not the responsibility of a control.  A control that prints itself seems odd.

**Comment by beto-rodriguez** [comment]
@gregsdennis Yeah I agree with you, maybe the best this library could do is return the control as an image but as I said wpf does it really easly

**Comment by arynsinha** [comment]
Plz Give some idea For print it with winForm
