### ISSUE TITLE
Request for TimeLine Chart/Scrollbar

### ISSUE THREAD

**Issue by guytwena** [beto-rodriguez/Live-Charts#97]
Hi,

I would like to request new feature;
I need chart that the number of items on the x Axis are fixed, for my needs scroll bar can be enough , time line is another option (like the stocks charts)

please let me know if it's possible.

Thanks in advance,

Guy

**Comment by beto-rodriguez** [comment]
Hello,  do you mean data pagination? I mean first page 0-50 second 50-100, 100-150 and so on

**Comment by guytwena** [comment]
Hi,

 

Thanks for getting back to me,

I didn’t meant pagination,

 

Good example is google finance ( <https://www.google.com/finance?q=aapl> https://www.google.com/finance?q=aapl)

That you have the data on the chart where the xAxis is hourly; 

You can scroll horizontal to view more data, but the data will still be  hourly (the units of the xAxis are fixed)

 

Thanks,

 

Guy

**Comment by gregsdennis** [comment]
I think he's asking for a fixed-scale on the x axis. So that when more data is added, the graph schools instead of redrawing at a new x scale.

**Comment by guytwena** [comment]
Yes, Exactly, 
And even for existing data let say you have 1000 items - you can decide that you want to view only 100 (scale of 100),  you will get scroll so you can move left or right to view the charts data

Thanks

**Comment by beto-rodriguez** [comment]
Interesting request this will be added in a future

**Comment by beto-rodriguez** [comment]
When this issue was created I was not able to see the link you send me, I was in one o those countries that bans google :( Now I see what you requested, this is already supported, not with a scroll bar but dragging the chart, currently zooming and panning might not work correctly because of 0.6.5 version changes, I will fix zooming and panning again when I fix all major changes, This issue will be open while I build an example.
If you really need it now all you need to do is use the Axis.Min and Axis.Max properties, for example pull 1000 points that X goes 0, 1, 2, 3, .... 999 then use the min and max properties to navigate only through the records you need, for example min = 0 max = 100, then min = 20 max = 120 and so on

This is done by panning automatically but I am not really sure if panning is working with 0.6.5

**Comment by pusaken** [comment]
Nope, zoom and pan do NOT work properly in the 0.6.5 release :-).
It behaves rather oddly, even on the very basic line chart example: data is disappearing or panning out of sight when zooming. If you zoom out to far, exception is thrown.

*hoping for the next version*: Nice library so far!

**Comment by catacon** [comment]
I have seen the same issue with a simple line chart as pusaken.  Zooming makes no sense.

**Comment by beto-rodriguez** [comment]
@catacon Zooming is not working now, 0.6.5 and again 0.6.6 change the library like 50% of the code, I will fix it when all major changes are done

**Comment by beto-rodriguez** [comment]
I am closing this issue and merging it in a new one with another issue to explain it better

**Comment by beto-rodriguez** [comment]
@guytwena panning is already fixed, click and drag in a line chart to see support this request

please let me know if this was what you wre looking for or I messed up

<img src="https://cloud.githubusercontent.com/assets/10853349/14480111/65c18a98-00eb-11e6-8ce2-bc7cf3d0fdfc.gif" />
